### ISSUE TITLE
"DuolingoException: Login failed"

### ISSUE THREAD

**Issue by omarecd** [KartikTalwar/Duolingo#102]
Dear Team.
I'm using this nice piece of code to check my duolingo points each day :)
I have not change anything, however since some few hours I am getting this.
**DuolingoException: Login failed**
Any ideas?

Thanks.
Omar C.

**Comment by joshcoales** [comment]
Yes, I've seen the same, and our automated testing started failing today too.
I've had a bit of a busy day so far today, but planning to start investigating it soon

**Comment by omarecd** [comment]
Thanks a lot... Keep us posted :)

**Comment by joshcoales** [comment]
Looks like a simple enough fix, I'll try and push a new package now, should be 0.5.4, if all goes according to plan

**Comment by joshcoales** [comment]
There we go, version 0.5.4 is published on pypi now:
https://pypi.org/project/duolingo-api/0.5.4/
Should work
