### ISSUE TITLE
get example sentences and tts via dictionary_page

### ISSUE THREAD

**Issue by bemitc** [KartikTalwar/Duolingo#110]
Any chance you could add a call to grab example sentences and their tts via the /api/1/dictionary_page endpoint? eg: https://www.duolingo.com/api/1/dictionary_page?lexeme_id=8c7f9bc995c812206852fe2323eead0f&from_language_id=en

**Comment by atmatto** [comment]
It's already possible using the `Duolingo.get_word_definition_by_id(self, lexeme_id)` function. Apparently it's not documented in the readme.
https://github.com/KartikTalwar/Duolingo/blob/9e552ba4b03be8dff44e1de6e55d7c845d53c897/duolingo.py#L681-L697
