### ISSUE TITLE
Module import breaks json.dumps()?

### ISSUE THREAD

**Issue by lidiaCirrone** [KartikTalwar/Duolingo#115]
Hi,

I'm trying to build a WP plugin that reads data from my Duolingo account and displays it in a shortcode. I have a .php file that decodes a json object generated by a .py file that uses this api. Locally it all works fine, but when I tried to go online the json object stopped working giving me NULL. I have no clue what's going on, but I've just found out that the problem happens when I import this duolingo module in my .py file. If I delete that line (and of course lose all the purpose of this project) and just generate a random object, it's all good, so it's not a php or wp related problem.

Basically, this is the .py
<pre>import json
import duolingo
test_object = {
   "avatar": "aaa",
    "username": "bbb",
    "streak": "ccc",
    "xp": "ddd",
    "creation_date": "eee",
    "learning_language": {
        "string": "fff",
        "level": "ggg",
        "level_percent": "hhh"
    },
    "all_languages": "iii"
}
print(json.dumps(test_object))</pre>
If I leave it like this, I get NULL when trying to retrieve the object in php. If I delete line 2, everything's ok. Any thoughts? I also tried to change the duolingo directory and files CHMOD permissions, maybe it's that but I chose the wrong ones?

**SIDE NOTE**
I know I could just write the whole thing in php (also since I don't need all the great things this api provides and I could keep it simple), I'm just being stubborn and want to understand why it works on my machine but not online.

**Comment by igorskh** [comment]
Hi @lidiaCirrone,

I couldn't reproduce this issue and it doesn't seem to be related to the this package, rather to the PHP/Python configuration on the server, e.g. the way you install Python modules and call this python script from the PHP script, especially when it works fine locally.

You can pm me, maybe I could help you to figure out.

**Comment by lidiaCirrone** [comment]
@igorskh 
thank you so much!
