### ISSUE TITLE
3rd Party Login

### ISSUE THREAD

**Issue by Antwohlf** [KartikTalwar/Duolingo#127]
Is it possible to log in via a 3rd party provider with this API (Facebook or Google being examples)? I have been receiving "login failed" errors but verified the login works on the website.

**Comment by igorskh** [comment]
As far as I know, it's not possible, what exactly are you trying to do? Simply submitting your Facebook/Google credentials won't work, the authentication has to take place in browser. After that you can use a JWT in this library.

**Comment by Antwohlf** [comment]
I apologize, I see now that this is a duplicate of https://github.com/KartikTalwar/Duolingo/issues/84

Thank you!

**Comment by Antwohlf** [comment]
Just to clarify, this should be as simple as 
lingo  = duolingo.Duolingo('username', jwt='token.from.browser')
correct?

I'm still getting    
```
 raise DuolingoException("Login failed")
duolingo.DuolingoException: Login failed 
```
errors with the token from a logged in browser. I've also tried specifying password and session_file as None in the duolingo constructor with the same result.

**Comment by igorskh** [comment]
@Antwohlf I'm afraid there is an issue with library implementation. 

The URL in this line:
https://github.com/KartikTalwar/Duolingo/blob/9e552ba4b03be8dff44e1de6e55d7c845d53c897/duolingo.py#L142 

has to be
```python
return https://www.duolingo.com/users/%s" % self.username 
```

Otherwise it returns a HTTP 302 and redirects in which case authorisation fails.

**Comment by adnanaga** [comment]
> @Antwohlf I'm afraid there is an issue with library implementation.
> 
> The URL in this line:
> 
> https://github.com/KartikTalwar/Duolingo/blob/9e552ba4b03be8dff44e1de6e55d7c845d53c897/duolingo.py#L142
> 
> has to be
> 
> ```python
> return https://www.duolingo.com/users/%s" % self.username 
> ```
> 
> Otherwise it returns a HTTP 302 and redirects in which case authorisation fails.

What is the difference here between the two lines

**Comment by adnanaga** [comment]
> @Antwohlf I'm afraid there is an issue with library implementation.
> 
> The URL in this line:
> 
> https://github.com/KartikTalwar/Duolingo/blob/9e552ba4b03be8dff44e1de6e55d7c845d53c897/duolingo.py#L142
> 
> has to be
> 
> ```python
> return https://www.duolingo.com/users/%s" % self.username 
> ```
> 
> Otherwise it returns a HTTP 302 and redirects in which case authorisation fails.

Just to highlight for others, the difference here is there is a "www." in front of Duolingo.com vs just https://duolingo.com...
