### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'password'

### ISSUE THREAD

**Issue by Josh2K** [KartikTalwar/Duolingo#32]
import duolingo
lingo  = duolingo.Duolingo('XXXX', password='XXXX')

is now generating the error:
TypeError: __init__() got an unexpected keyword argument 'password'

**Comment by ZuluPro** [comment]
For me there's no error in code.
Could you try to erase and rewrite this line ?

**Comment by Josh2K** [comment]
tried rewriting line and upgrading duolingo-api  - same error:
TypeError: __init__() got an unexpected keyword argument 'password'

**Comment by ZuluPro** [comment]
@Josh2K  Could you give the full traceback ?

**Comment by Josh2K** [comment]
hmmm, I was running this with python 2.7.6 on windows 10.  I just tried the same code on Linux python 2.7.6 and it worked.  Must be something wrong on my side.
