### ISSUE TITLE
Can't create Duolingo object

### ISSUE THREAD

**Issue by cmd16** [KartikTalwar/Duolingo#46]
I installed and imported duolingo. I tried with and without adding my password, and both times I got this error message:

`Traceback (most recent call last):
  File "/Users/cat/PycharmProjects/duolingo/duolingo_proj.py", line 2, in <module>
    lingo = duolingo.Duolingo('CatherineD576833')
  File "/anaconda/lib/python3.5/site-packages/duolingo.py", line 25, in __init__
    self.user_data = Struct(**self._get_data())
  File "/anaconda/lib/python3.5/site-packages/duolingo.py", line 61, in _get_data
    get = self.session.get(self.user_url).json()
  File "/anaconda/lib/python3.5/site-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/anaconda/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/anaconda/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

If I typed something wrong, the documentation should be edited to provide a clearer example. If I typed this right, then there is an issue that needs to be fixed. Seems like a great API but I can't access any of it right now if I can't even make an object.

**Comment by exofudge** [comment]
Cannot recreate on my end, how did you install? Appears that the module isn't correctly receiving the data from the API, what response do you get when you navigate here [https://www.duolingo.com/users/CatherineD576833](https://www.duolingo.com/users/CatherineD576833)?

**Comment by mlutze** [comment]
I was getting the same error. It appears the request was receiving a 429 (too many requests) response.
I had installed through `pip install duolingo-api` with Python 3.5 on Windows 10.
Using the `duolingo.py` file from the Github repository rather than the one in the pip package resolved the issue for me.

**Comment by exofudge** [comment]
Ah I forgot about downloading using pip, @KartikTalwar the pip package needs to be updated to stop people getting this issue.

**Comment by cmd16** [comment]
Thanks! I tried that and it works now.
