### ISSUE TITLE
issue with get_known_words

### ISSUE THREAD

**Issue by cmd16** [KartikTalwar/Duolingo#47]
So I was trying to use duolingo.py, but suddenly get_known_words() stopped working for some reason. It was working earlier, and then suddenly python started throwing me a KeyError. I can't recall changing anything. I created a Duolingo object called lingo, passing in the username and password. Then was the problem line:

`print(lingo.get_known_words('fr'))`

Here is the error message, which by the way appeared with every language I tried (i.e., several different languages I am learning):

`Traceback (most recent call last):
  File "/Users/cat/PycharmProjects/duolingo/duolingo_proj.py", line 6, in <module>
    print(lingo.get_known_words('fr'))
  File "/anaconda/lib/python3.5/duolingo.py", line 341, in get_known_words
    for topic in self.user_data.language_data[lang]['skills']:
KeyError: 'fr'`

Am I typing something wrong, or did the function just stop working?

Edit: noticed that on the website itself I was having trouble seeing wordlists on some languages, incidentally the same ones I tried when noticing the python error. get_known_words() worked just fine with German.

**Comment by cmd16** [comment]
Okay so it seems to have just been a brief issue that resolved itself; all languages work now. Idk what that was, but closing the issue now since it seems to have been resolved? Weird.

**Comment by cmd16** [comment]
Never mind it's still not working.

**Comment by cmd16** [comment]
Ok I think I know what the issue is. It depends on what language I currently have selected online. Currently it only works if online I am on the page for the language I am trying to get the words for. For example:
<img width="724" alt="screen shot 2017-08-11 at 9 23 57 pm" src="https://user-images.githubusercontent.com/23747622/29236650-7a7796fc-7edb-11e7-8a00-ce3b335f61a5.png">
When this is what my duolingo website looks like, I can only get the wordlist for Italian.

**Comment by joshcoales** [comment]
I think this is working now? Closing ticket
