### ISSUE TITLE
pypi.python.org old version

### ISSUE THREAD

**Issue by zafai** [KartikTalwar/Duolingo#53]
Hello,

I check the version of the "duolingo-api" package on pypi and it seems that version 0.3 is really old (uploaded 2015-11-22) is it possible that you can upload a new version?

Thank you in advance.

**Comment by TiloGit** [comment]
hi, see my #52 for info how to install latest from github direct.

**Comment by zafai** [comment]
@TiloGit Thank you for your reply and the link for your instructions.
I got a working environment in docker and also in my dev-env.
The pipy repo is just nice because I could install the package with one command in my Docker Build Script 👍

**Comment by joshcoales** [comment]
This has been updated now
