### ISSUE TITLE
How to find XP Progress

### ISSUE THREAD

**Issue by andreasscherbaum** [KartikTalwar/Duolingo#74]
The Duolingo website shows the daily XP progress (like: 79 out of goal 20), however it seems this value is not available through the API.

Anyone knows how to fetch the daily progress using Python?

**Comment by igorskh** [comment]
Hi Andreas, 

It's available through the API, but you need to use another endpoint with mandatory authentication, currently it is: 

`https://www.duolingo.com/2017-06-30/<userID>?fields=xpGoal,xpGains `

You will get the response like this:
```json
{
  "xpGains": [
    {
      "eventType": "PRACTICE",
      "xp": 24,
      "skillId": null,
      "time": 1579392602
    },

  ],
  "xpGoal": 10
}
```

However, those fields are available if userID corresponds to the authenticated user. So, you can get them only for your own account.

Regards,
Igor

**Comment by andreasscherbaum** [comment]
@igorskh So you are saying that's not possible with this tool here? Using duolingo.Duolingo?
I don't see how I can specify a different API endpoint.

**Comment by igorskh** [comment]
You're right base URL isn't configurable at the time. Without changing the code, I can suggest the following workaround:

```
import duolingo 

lingo  = duolingo.Duolingo('username', password='password')
lingo.user_url = "https://www.duolingo.com/2017-06-30/users/%d?fields=xpGoal,xpGains"%lingo.user_data.id
data = lingo._get_data()

print(data)
```

But it definitely needs to be fixed.

**Comment by igorskh** [comment]
I don't know how reasonable the PRs are, because I see some are there for quite a while without a review.

**Comment by joshcoales** [comment]
This would be a very useful endpoint to add, yeah. Should be relatively easy to add too. I could throw it in my big PR if you want, but seems easy to add a new one for this.
@KartikTalwar has only been gone a month, so I'm still hopeful he'll return and review those (including my) PRs. January is a busy time of year for lots of folks.

**Comment by KartikTalwar** [comment]
Hey all, sorry I have not been as active here and haven't been able to dedicate a lot of time as of past few weeks towards this. I'm glad that you have been kind enough to contribute and help address known issues and features and if either of you are interested in helping maintain this, I'd be more than happy to make you a contributor to the repo.

I'll aim to set aside some time to review all outstanding PRs regardless :-)

**Comment by joshcoales** [comment]
Yeah, I wouldn't mind helping out where I can

**Comment by joshcoales** [comment]
This got solved by that merged PR by the way, so I shall close this issue now
