### ISSUE TITLE
Google Login unavailable

### ISSUE THREAD

**Issue by kookiedough** [KartikTalwar/Duolingo#84]
API Doesn't work if Google login is used with Duolingo

**Comment by igorskh** [comment]
Can you give more information on what and how you are trying to do and what issue you are facing?

If you trying to use your Google login/password with this library it won't work, because OAuth is not implemented.

**Comment by kookiedough** [comment]
i made my Duolingo account using Google login and thus it doesn't work with my account

**Comment by EricHier** [comment]
Is there any solution to using a Duolingo account created using the Google Sign-In?

**Comment by igorskh** [comment]
You can authorize with Google Sign-In in a browser, then lookup JWT in Developer Tools under Network tab, and use it as a named argument `jwt` in the `Duolingo` class:
```python
import duolingo
lingo  = duolingo.Duolingo('username', jwt='your_jwt_here')
```

I can't think of a straightforward method to authorize with Google account from Python script.

**Comment by EricHier** [comment]
Hi @igorskh :) do you have to get a new jwt now and then or does that jwt stay functioning forever?

**Comment by igorskh** [comment]
> Hi @igorskh :) do you have to get a new jwt now and then or does that jwt stay functioning forever?

Hey @EricHier, technically Duolingo JWT does have an expiration date, but from what I see it's set to the year 2169, so practically it should not :) You can decode content of JWT with jwt.io and see it yourself. So not forever, but quite long, they might have some revoking mechanisms though, you might still need to get a new token sometimes.

**Comment by adnanaga** [comment]
Did anyone else get this to work ?
