### ISSUE TITLE
Feature request - get Lingots amount

### ISSUE THREAD

**Issue by TiloGit** [KartikTalwar/Duolingo#95]
hi, is there an URL/API to report the amount of Lingots  I have?

**Comment by igorskh** [comment]
Hi, 

With the latest version you can use `get_data_by_user_id` method like this:
```python
import duolingo

lingo = duolingo.Duolingo('<username>', '<password>')
user_data_resp = lingo.get_data_by_user_id(['lingots'])
print(user_data_resp)
print(user_data_resp['lingots'])
```

It should show something like this:
```text
{'lingots': 11014}
11014
```

This method calls this URL: /2017-06-30/users/<userID>?fields=lingots 

You can also check most of available for `get_data_by_user_id` method fields here:
https://duolingo-api.roundeasy.vercel.app/#operation/getUser

They can be easily passed in a list to the method like this:
```python
user_data_resp = lingo.get_data_by_user_id(['lingots', 'totalXp'])
```

**Comment by TiloGit** [comment]
super danke.

**Comment by TiloGit** [comment]
fyi, in the past this could be called with no field specified but now (well for a while) you need to call it with fields. 

e.g: 
```py
#user_data_resp = lingo.get_data_by_user_id()
user_data_resp = lingo.get_data_by_user_id(['lingots','totalXp','monthlyXp','weeklyXp','gems'])
```
